name: update_captcha_submodule
on:
  repository_dispatch:
    types: [captcha_updated]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print contexts
        env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
              ENV_CONTEXT: ${{ toJson(env) }}
              VARS_CONTEXT: ${{ toJson(vars) }}
              JOB_CONTEXT: ${{ toJson(job) }}
              STEPS_CONTEXT: ${{ toJson(steps) }}
              RUNNER_CONTEXT: ${{ toJson(runner) }}
              SECRETS_CONTEXT: ${{ toJson(secrets) }}
              STRATEGY_CONTEXT: ${{ toJson(strategy) }}
              MATRIX_CONTEXT: ${{ toJson(matrix) }}
              NEEDS_CONTEXT: ${{ toJson(needs) }}
              INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: |
              echo "******************************"
              echo "github:" "$GITHUB_CONTEXT"
              echo "******************************"
              echo "env:" "$ENV_CONTEXT"
              echo "******************************"
              echo "vars:" "$VARS_CONTEXT"
              echo "******************************"
              echo "job:" "$JOB_CONTEXT"
              echo "******************************"
              echo "steps:" "$STEPS_CONTEXT"
              echo "******************************"
              echo "runner:" "$RUNNER_CONTEXT"
              echo "******************************"
              echo "secrets:" "$SECRETS_CONTEXT"
              echo "******************************"
              echo "strategy:" "$STRATEGY_CONTEXT"
              echo "******************************"
              echo "matrix:" "$MATRIX_CONTEXT"
              echo "******************************"
              echo "needs:" "$NEEDS_CONTEXT"
              echo "******************************"
              echo "inputs:" "$INPUTS_CONTEXT"
              echo "******************************"
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
    
      - name: Update submodules
        env:
            GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
            GIT_AUTH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
        run: |
            git config user.name "prosoponator[bot]"
            git config user.email "dev@prosopo.io"
            git submodule update --remote a
            git add .
            git commit -m "Updated a submodule"
            git push